#ifndef UI_STATE_H
#define UI_STATE_H

enum UserInterfaceState
{
    UI_STATE_DEFAULT,

    UI_STATE_SELECT_AREA_WITH_MOUSE,

    UI_STATE_CURSOR_MOVING,
    UI_STATE_VIEW_RESIZING,

    UI_STATE_KEYBOARD_SAMPLE_DRAG,
    UI_STATE_MOUSE_DRAG_SAMPLE_START,
    UI_STATE_MOUSE_DRAG_SAMPLE_LENGTH,

    UI_STATE_MOUSE_DRAG_MONO_LOWPASS,
    UI_STATE_MOUSE_DRAG_MONO_HIGHPASS,

    UI_STATE_DISPLAY_FREQUENCY_SPLIT_LOCATION,
    UI_STATE_DISPLAY_TIME_SPLIT_LOCATION,

    UI_STATE_MOUSE_DRAG_NUMERIC_INPUT,

    UI_STATE_RESIZE_MAINVIEW,

    UI_STATE_MOVE_LOOP_SECTION
};

#endif // UI_STATE_H